from typing import Protocol, List, Optional
from uuid import UUID
from ..domain.tour import Passeio


class IPasseioRepositorio(Protocol):
    def adicionar(self, passeio: Passeio) -> None: ...

    def listar_todos(self) -> List[Passeio]: ...

    def listar_por_guia(self, guia_id: UUID) -> List[Passeio]: ...

    def obter(self, id: UUID) -> Optional[Passeio]: ...

    def atualizar(self, passeio: Passeio) -> None: ...

    def deletar(self, id: UUID) -> None: ...
